### ISSUE TITLE
Request for Leaderboard Results

### ISSUE THREAD

**Issue by smartkeithel** [DMIRLAB-Group/SADGA#1]
Hi SADGA Team, thank you so much for uploading the code. I have seen that you have uploaded the results only for the baseline. Can you upload the Spider Leaderboard results as well? If not possible, it will be very helpful if you can provide at least the dev predicted SQLs of SADGA-GAP so that I can compare your results directly to mine. 

Thanks in Advance!

**Comment by Yuan0320** [comment]
Hi, we are sorry that we have not uploaded the code of other PLMs versions of SADGA, we will organize the code and release them soon. Regarding your request for the dev predicted SQLs of SADGA + GAP, we upload the results and you can download them from [https://drive.google.com/file/d/1WDVSPflAYiKqgYX5DMsIwLJp-mUNPr3w/view?usp=sharing](https://drive.google.com/file/d/1WDVSPflAYiKqgYX5DMsIwLJp-mUNPr3w/view?usp=sharing). If you have any other questions, please let us know.

**Comment by smartkeithel** [comment]
Thank you so much for the super fast response!
