### ISSUE TITLE
Could you share the trained model?

### ISSUE THREAD

**Issue by AtulKumar4** [DMIRLAB-Group/SADGA#2]

**Comment by Yuan0320** [comment]
Hi, our trained model, predict_sql.txt file and other training files can be downloaded here:[[logdir.zip](https://drive.google.com/file/d/1Ip5_hsLb4gwoDbsAuStAQ7up5KtFLb9b/view?usp=sharing)].
Regarding the trained model with other PLMs, we are sorry that we have not uploaded the code and the trained model of other PLMs versions of SADGA, we will organize and release them soon. 
BTW, we also upload the dev predicted SQLs of SADGA + GAP results and you can download them from [https://drive.google.com/file/d/1WDVSPflAYiKqgYX5DMsIwLJp-mUNPr3w/view?usp=sharing](https://drive.google.com/file/d/1WDVSPflAYiKqgYX5DMsIwLJp-mUNPr3w/view?usp=sharing) if you need them. 
Please let us know if you have any other questions.

**Comment by AtulKumar4** [comment]
@Yuan0320 Thank you for the quick response.
there are ".infer" files at different steps and 1 model checkpoint in logdir.zip. So I need to use the ".infer" file or model checkpoint for inference?
Btw I am trying to inference on the custom SQLite database using infer.py.
Thanks

**Comment by Yuan0320** [comment]
@AtulKumar4 If you need to inference on the custom SQLite database, among logdir.zip you only use the model checkpoint for inference. And you need to preprocess your custom SQLite database and your samples to Spider's data form and perform preprocessing before inference.

Additionally, the logdir.zip are described below:
1. model_checkpoint-00038100: our best trained model, from step 38100.
2. log.txt: training logs.
3. res/sadga_glove_stepxxx.infer: detailed inference results of the Spider dev dataset from the model in step xxx. (including beams result, score, etc.)
4. res/predict_sql_stepxxx.txt: the final predicted SQL result of the Spider dev dataset from the model in step xxx. It is extracted by the corresponding .infer file. (see line 112-124 in sadgasql/commands/infer.py)
5. res/acc_res_stepxxx.txt: the detailed accuracy result file via the official [Spider Evaluation](https://github.com/taoyds/spider), the input predicted file it needs is predict_sql_stepxxx.txt.

**Comment by AtulKumar4** [comment]
@Yuan0320 Thankyou. This helps.
I will share the update
