### ISSUE TITLE
Can you please share bert config?

### ISSUE THREAD

**Issue by wickcode** [DMIRLAB-Group/SADGA#3]
Hi @Yuan0320 @DMIRLAB ,

Thank you for the code. I was wondering what changes I can do in config to make it use bert embeddings?

**Comment by Yuan0320** [comment]
Hi @wickcode, the detailed configs under different pre-trained models can be found in Section D of the [paper](https://arxiv.org/abs/2111.00653). We will organize the release of the code of other PLMs versions as soon as possible! We are sorry for that.

**Comment by wickcode** [comment]
Hi @Yuan0320,

Thank you for the reply.

I looked at the python files and I did not find any code for Bert. I can fill the config based on the paper, but can you please point to the relevant code?
For example, I looked at the encoder: https://github.com/DMIRLAB-Group/SADGA/blob/main/sadgasql/models/encoder/encoder.py

Am I looking at the wrong place? Please let me know.

Thank you for your help.

**Comment by Yuan0320** [comment]
Hey @wickcode, you are right, up to now we have only released codes of the raw SADGA model, and have not released any code for BERT or GAP. We are working toward that and I promise you that I will open-source the code of the BERT version asap, maybe within a month. We are really sorry for that.
BTW, if your needs are urgent, you can refer to the code of [RATSQL](https://github.com/Microsoft/rat-sql). For using BERT, our implementation is basically the same as the RATSQL code.

**Comment by Yuan0320** [comment]
Hi @wickcode, we have released codes for other PLMs, and uploaded the model checkpoints and associated result files:

our best trained checkpoints, predict_sql files and accuracy_result files can be downloaded in here:
[[logdir.zip](https://drive.google.com/file/d/1Ip5_hsLb4gwoDbsAuStAQ7up5KtFLb9b/view?usp=sharing)] (GloVe: 65.6)
[[logdir.zip](https://drive.google.com/file/d/17lUvKq3BsPTJzUSSa2ihjrGe0t_fJVMy/view?usp=sharing)] (Bert-large: 71.6)
[[logdir.zip](https://drive.google.com/file/d/1yuDoWCzcUq4MCGRqHFIM9Aopf1qfdUNC/view?usp=sharing)] (GAP: 73.9).

Please let us know if you have any other questions.

**Comment by wickcode** [comment]
Thank you very much.
