### ISSUE TITLE
All the checkpoints are same.

### ISSUE THREAD

**Issue by AtulKumar4** [DMIRLAB-Group/SADGA#4]
Thanks for updating the repo and sharing the source code.

[logdir.zip] (GloVe), [logdir.zip] (Bert-large), and [logdir.zip] (GAP) -  I found all the logdir.zip points to the model checkpoint.

**Comment by Yuan0320** [comment]
Hi @AtulKumar4, we have uploaded the model checkpoints and associated result files, and updated the links in README.md.
Please let us know if you have any other questions.

**Comment by AtulKumar4** [comment]
@Yuan0320  Thank you for the quick response.
