### ISSUE TITLE
GAP model issue at inference time

### ISSUE THREAD

**Issue by AtulKumar4** [DMIRLAB-Group/SADGA#5]
@Yuan0320 
FileNotFoundError: [Errno 2] No such file or directory: 'plm\\gap\\pytorch_model.bin'

I have kept the pretrained_checkpoint in plm->gap folder. Could you help me with the way to get pytorch_model.bin file?

Thanks
Atul

**Comment by Yuan0320** [comment]
@AtulKumar4
Regarding the inference stage of SADGA + GAP with our best model checkpoint (spider dev: 73.9), you can follow these steps step by step:

1. Download the pertained model GAP from [pretrained-checkpoint](https://gap-text2sql-public.s3.amazonaws.com/checkpoint-artifacts/pretrained-checkpoint) (pretrained_checkpoint -> pytorch_model.bin), and put `pytorch_model.bin` into the directory `plm/gap`.

``` bash
mkdir -p plm/gap
```

```
└── plm
    └── gap
        └── pytorch_model.bin
```

2. Download our best pretrained model checkpoint from here ([[logdir.zip](https://drive.google.com/file/d/1yuDoWCzcUq4MCGRqHFIM9Aopf1qfdUNC/view?usp=sharing)] (GAP: 73.9)).

```
└── SADGA-main
    ├── configs
    ├── dataset
    ├── evaluation
    ├── logdir
        └── sadga_gap_bs=6_lr=1.0e-04_blr=1.0e-05
            └── model_checkpoint-00051000
    ├── plm
    ├── preprocess_data
    ├── run.py
    ├── sadga-gap-run.jsonnet
    ├── sadgasql
    └── third_party
```

3. In `sadga-gap-run.jsonnet`, for infer, start_step: 31000 --> start_step: 51000.

4. python run.py --mode infer --config sadga-gap-run.jsonnet 
    - get the predicted SQLs result (`predict_sql_step51000.txt`).

5. python run.py --mode eval --config sadga-gap-run.jsonnet 
    - input the `predict_sql_step51000.txt` into the Spider official evaluation, get the final accuracy result file `acc_res_step51000.txt`.

**Comment by AtulKumar4** [comment]
@Yuan0320 Yeah I did all these steps. But the problem I am facing is that I don't see pytorch_model.bin. All I can download is pretrained_checkpoint. Could you help me where to get pytorch_model.bin? Or I am missing something here?
![image](https://user-images.githubusercontent.com/26081785/151360870-fc6b2d39-9d8a-47a4-b8f4-e74c6e97172f.png)

**Comment by Yuan0320** [comment]
@AtulKumar4 
Oh sorry, in fact, this is `pytorch_model.bin`, i.e., rename `pretrained-checkpoint` to `pytorch_model.bin`. 

Thanks for mentioning this issue!

**Comment by AtulKumar4** [comment]
@Yuan0320 Thanks it worked.

**Another Bug:
start_step in sadga-gap-run.jsonnet and max_steps in sadga-gap-config.jsonnet needs to be replaced with 51000  for gap in order to run otherwise it will though this error**

Exception: Attempting to infer on untrained model in logdir/sadga_gap_bs=6_lr=1.0e-04_blr=1.0e-05, step=41000.

The error goes away once I set maximum steps and start steps to 51000 steps as the last checkpoint saved at 51000 steps.

@Yuan0320  Could you please correct me if I missed something?

**Comment by Yuan0320** [comment]
@AtulKumar4 
Thanks for your careful discovery! In fact, `start_step` is the first checkpoint to test after training, e.g., `start_step` is 31000, then all checkpoints during 31000-61000 steps will be tested (the interval is 1000 steps, and `max_steps` is 61000).

If you test only the 51000-step checkpoint (no other checkpoints in the folder), you can set `start_step` to 51000. In fact, the code will test all models between 51000-61000 steps, but no other models have been found (52000-step checkpoint, etc.), which is the reason for the error, but it doesn't affect it to generate the result file of the 51000-step checkpoint.

**Comment by AtulKumar4** [comment]
@Yuan0320 Thank you for the clear explanation and quick response.
