### ISSUE TITLE
Issue in inference using custom database schema

### ISSUE THREAD

**Issue by AtulKumar4** [DMIRLAB-Group/SADGA#6]
@Yuan0320  Hi,

I have preprocessed my SQLite(which includes only two tables ) into spider format. But When I load the GAP model I get this error.

RuntimeError: Error(s) in loading state_dict for EncDecModel:
	size mismatch for decoder.rule_logits.2.weight: copying a param with shape torch.Size([97, 128]) from checkpoint, the shape in current model is torch.Size([0, 128]).
	size mismatch for decoder.rule_logits.2.bias: copying a param with shape torch.Size([97]) from checkpoint, the shape in current model is torch.Size([0]).
	size mismatch for decoder.rule_embedding.weight: copying a param with shape torch.Size([97, 128]) from checkpoint, the shape in current model is torch.Size([0, 128]).
	size mismatch for decoder.terminal_logits.2.weight: copying a param with shape torch.Size([5, 128]) from checkpoint, the shape in current model is torch.Size([3, 128]).
	size mismatch for decoder.terminal_logits.2.bias: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([3]).
	size mismatch for decoder.terminal_embedding.weight: copying a param with shape torch.Size([5, 128]) from checkpoint, the shape in current model is torch.Size([3, 128]).
	size mismatch for decoder.node_type_embedding.weight: copying a param with shape torch.Size([55, 64]) from checkpoint, the shape in current model is torch.Size([2, 64]).

Thanks

**Comment by Yuan0320** [comment]
Hi @AtulKumar4, maybe you can try to keep our uploaded files `preprocess_data/gap/` except `dec/train.jsonl`, `dec/dev.jsonl`, `enc/train.jsonl` and `enc/dev.jsonl`.

Your custom data (change to **dev**.json):

```
└── dataset
    ├── database
    ├── dev.json
    └── tables.json
```

Before running preprocess:

```
└── preprocessed_data
    └── gap
        ├── dec (empty)
        ├── dec_vocab.json
        ├── enc
            ├── added_tokens.json
            ├── merges.txt
            ├── ...
            └── vocab.json
        ├── grammar_rules.json
        └── observed_productions.json
```

After running preprocess:

```
└── preprocessed_data
    └── gap
        ├── dec
            └── dev.jsonl
        ├── dec_vocab.json
        ├── enc
            ├── added_tokens.json
            ├── dev.jsonl
            ├── merges.txt
            ├── ...
            └── vocab.json
        ├── grammar_rules.json
        └── observed_productions.json
```

**Comment by AtulKumar4** [comment]
@Yuan0320  is it mandatory to keep the "sql" key in dev.json for inference on custom schema?

**Comment by Yuan0320** [comment]
@AtulKumar4 not mandatory, but you need to modify the preprocessing code: remove the code related to "sql".
There is no `dec/dev.jsonl` file after preprocessing because the data preprocessing of the decoder is for the ground truth.

**Comment by AtulKumar4** [comment]
@Yuan0320 model is predicting the "Terminal" keyword whenever there is any value in the input query.
For example, all the orders where the amount exceeds 5000.

Is there any way to fill the terminal keyword?

**Comment by Yuan0320** [comment]
@AtulKumar4 Our work only focuses on the Spider challenge - Exact Set Match **without** Values. Our current models do not predict any value in SQL conditions, and we do not provide execution accuracies. We are very sorry for this.

Regarding execution with values, maybe you can refer to Leaderboard - Execution with Values of [Spider](https://yale-lily.github.io/spider).

**Comment by AtulKumar4** [comment]
@Yuan0320 Thankyou
